### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by galulex** [toysshopdevelop/toysshop#12]
Everything should be in locales

**Comment by kokosko** [comment]
en + ru?

**Comment by galulex** [comment]
en + ru

**Comment by kokosko** [comment]
www.example.com/ru/someproduct
or
www.example.com/someproduct?locale=ru
?

**Comment by galulex** [comment]
keep locale in session

**Comment by galulex** [comment]
@kokosko Let us do in next way:
Set the default locale to `ru` in app configs
Will keep only one `ru` locale

**Comment by kokosko** [comment]
add gem i18n-rails
change locale in aplication.rb
